### ISSUE TITLE
Bounce Mode

### ISSUE THREAD

**Issue by endercrest** [endercrest/VoidSpawn#19]
Instead of teleporting, launch the player upwards so that they bounce along the void. Does this go on forever?

**Comment by SlimeDog** [comment]
Possibly forever, but I prefer something like:

bounce-seconds: 15

teleport-target: x y z [world]
or
teleport-target: [world] # which would go to spawnpoint

**Comment by endercrest** [comment]
@SlimeDog So they bounce for 15 seconds then get teleported to the specified location?

**Comment by SlimeDog** [comment]
That's the idea. There may be a more general way to encode the data. Probably _bounce_ should be allowed in any mode. Then the teleport target isn't needed.

I use command mode (**mvtp**), because the teleport target is in a different world. (Perhaps **/set world** does that;  I didn't try.) So I would configure something like:

`world:
  mode: command
  command: mvtp e:world_void:0.5,64,0.1:0:0
  offset: 0
  bounce: 15`

**Comment by endercrest** [comment]
@SlimeDog Ok, by the way it is possible to set the spawn for a different world. /vs set (world). The world is not the name of the current world you are in but the world that you are setting it for.

I will hopefully get to this sometime soon. I am currently working on a fairly large update for https://github.com/endercrest/ColorCube

**Comment by SlimeDog** [comment]
Good to know about **/vs set**. That makes my configuration easier. Just set the (same) spawn in each world, and I'm good to go. :)

No hurry on the bounce. It's just a fun addition. Default should be 0, of course.

**Comment by SlimeDog** [comment]
Any time to add this? It's been a while. :)

**Comment by endercrest** [comment]
Added via the options command in V1.19.3

**Comment by SlimeDog** [comment]
Excellent. Please see [#86](https://github.com/endercrest/VoidSpawn/issues/86).
